# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Compile and package
        run: |
          python3 ./setup.py install --prefix /tmp/out

      - name: Test code
        run: |
          sudo python3 ./setup.py test
